version: "3.7"

services:
  activemq:
    image: 'webcenter/activemq:latest'
    ports:
      - '8161:8161'
      - '61616:61616'
      - '61613:61613'
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_CONFIG_MINMEMORY=1024
      - ACTIVEMQ_CONFIG_MAXMEMORY=4096
      - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
    restart: always